/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_unicredit_cuHE_jcuHE */

#ifndef _Included_eu_unicredit_cuHE_jcuHE
#define _Included_eu_unicredit_cuHE_jcuHE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_unicredit_cuHE_jcuHE
 * Method:    encrypt
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_eu_unicredit_cuHE_jcuHE_encrypt
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
